logical_technologies:
  -
   name: SAMPLES_PATH
   type: File
   physical_technologies:
      development:
        path: samples/files/
      test:
        path: samples/files/
      production:
        path: samples/files/
  -
   name: MYSQL_DATABASE
   type: MySQL
   physical_technologies:
      development:
        host: 127.0.0.1
        port: 3306
        user: miquel
        password: supct2335
        database: shark_tests
      test:
        host: 127.0.0.1
        port: 3306
        user: miquel
        password: supct2335
        database: shark_tests
      production:
        host: 127.0.0.1
        port: 3306
        user: miquel
        password: supct2335
        database: shark_tests
  -
   name: SQLITE3_PATH
   type: SQLite3
   physical_technologies:
      development:
        file: samples/files/data/test.db
      test:
        file: samples/files/data/test.db
      production:
        file: samples/files/data/test.db