logical_technologies:
  -
   name: CUSTOMERS
   type: File
   physical_technologies:
      development: /home/miquel/app/development
      test: /home/miquel/app/test
      production: /home/miquel/app/production
  -
   name: MYSQL_DATABASE
   type: MySQL
   physical_technologies:
      development:
        host: development_server
        port: 1521
        user: development_user,
        password: development_user_password,
        database: development_db
      test:
        host: test_server
        port: 1521
        user: test_user,
        password: test_user_password,
        database: test_db
      production:
        host: production_server
        port: 1521
        user: production_user,
        password: production_user_password,
        database: production_db
  -
   name: ORACLE_DATABASE
   type: Oracle
   physical_technologies:
      development:
        host: development_server
        port: 1522
        user: development_user,
        password: development_user_password,
        database: development_db
        schema: development
      test:
        host: test_server
        port: 1522
        user: test_user,
        password: test_user_password,
        database: test_db
        schema: test
      production:
        host: production_server
        port: 1522
        user: production_user,
        password: production_user_password,
        database: production_db
        schema: production